export const posts = [
  {
    id: 1,
    username: "meme_warrior",
    time: "12 menit",
    caption: "Kaget liat tagihan pas tanggal tua 😭💸",
    avatar: require("./assets/PP/pp3.jpg"),
    image: require("./assets/Post/pp3.png"),
    hashtags: ["#lucu", "#meme"],
  },
  {
    id: 2,
    username: "coding_boy",
    time: "25 menit",
    caption: "Error hilang setelah restart VS Code 🔧🤓",
    avatar: require("./assets/PP/pp6.jpg"),
    image: require("./assets/Post/pp6.png"),
    hashtags: ["#ngoding", "#tips"],
  },
  {
    id: 3,
    username: "ibu_kreatif",
    time: "1 jam",
    caption: "DIY hiasan meja dari barang bekas 🛠️✨",
    avatar: require("./assets/PP/pp9.jpeg"),
    image: require("./assets/Post/pp9.png"),
    hashtags: ["#DIY", "#rumah"],
  },
  {
    id: 4,
    username: "ngopi_dulu",
    time: "1 jam 20 menit",
    caption: "Espresso selalu jadi solusi ☕❤️",
    avatar: require("./assets/PP/pp4.png"),
    image: require("./assets/Post/pp4.png"),
    hashtags: ["#kopi", "#moodbooster"],
  },
  {
    id: 5,
    username: "si_pendaki",
    time: "2 jam",
    caption: "Sunrise dari puncak itu nggak ada obatnya 🌄🥾",
    avatar: require("./assets/PP/pp5.jpg"),
    image: require("./assets/Post/pp5.png"),
    hashtags: ["#nature", "#adventure"],
  },
  {
    id: 6,
    username: "chef_kilat",
    time: "2 jam 30 menit",
    caption: "Masak mie level dewa 🍜🔥",
    avatar: require("./assets/PP/pp2.png"),
    image: require("./assets/Post/pp2.png"),
    hashtags: ["#masak", "#cepat"],
  },
  {
    id: 7,
    username: "si_meong",
    time: "3 jam",
    caption: "Kucingku nonton anime sekarang 😹📺",
    avatar: require("./assets/PP/pp7.jpg"),
    image: require("./assets/Post/pp7.png"),
    hashtags: ["#kucing", "#weeb"],
  },
  {
    id: 8,
    username: "jalan_terus",
    time: "4 jam",
    caption: "Kena hujan pas naik motor, tapi tetep happy 🌧️🛵",
    avatar: require("./assets/PP/pp10.png"),
    image: require("./assets/Post/pp10.png"),
    hashtags: ["#travel", "#random"],
  },
  {
    id: 9,
    username: "band_garasi",
    time: "5 jam",
    caption: "Latihan band dadakan tapi vibes-nya dapet 🎸🎤",
    avatar: require("./assets/PP/pp1.jpg"),
    image: require("./assets/Post/pp1.png"),
    hashtags: ["#musik", "#garasi"],
  },
  {
    id: 10,
    username: "sketsa_harapan",
    time: "6 jam",
    caption: "Sketsa sambil dengerin hujan, chill banget 🎨🌧️",
    avatar: require("./assets/PP/pp8.jpeg"),
    image: require("./assets/Post/pp8.png"),
    hashtags: ["#seni", "#relax"],
  },
];
