export const posts = [
  {
    id: 1,
    username: "anak_meme",
    time: "10 menit",
    caption: "Meme segar buat hari Senin 😎💥",
    avatar: require("./assets/Post/pp1.png"),
    image: require("./assets/PP/pp1.jpg"),
    hashtags: ["#funny", "#olahraga"],
  },
  {
    id: 2,
    username: "ngoding_dev",
    time: "25 menit",
    caption: "Fix bug sambil ngopi itu seni tersendiri ☕👨‍💻",
    avatar: require("./assets/Post/pp2.png"),
    image: require("./assets/PP/pp2.png"),
    hashtags: ["#developer", "#nightlife"],
  },
  {
    id: 3,
    username: "bunda_hebat",
    time: "40 menit",
    caption: "Masakan pertama hari ini sukses besar! 🍲🥰",
    avatar: require("./assets/Post/pp3.png"),
    image: require("./assets/PP/pp3.jpg"),
    hashtags: ["#makan", "#keluarga"],
  },
  {
    id: 4,
    username: "kopi_senja",
    time: "1 jam",
    caption: "Nikmati senja dengan kopi hangat dan lagu lawas 🎶☕",
    avatar: require("./assets/Post/pp4.png"),
    image: require("./assets/PP/pp4.png"),
    hashtags: ["#kopi", "#santai"],
  },
  {
    id: 5,
    username: "pendaki_halu",
    time: "1 jam 30 menit",
    caption: "Puncak memang capek, tapi pemandangannya worth it banget! 🏔️❤️",
    avatar: require("./assets/Post/pp5.png"),
    image: require("./assets/PP/pp5.jpg"),
    hashtags: ["#travel", "#gunung"],
  },
  {
    id: 6,
    username: "dapur_digital",
    time: "2 jam",
    caption: "Eksperimen masakan fusion hari ini, siapa mau coba? 🍛🔥",
    avatar: require("./assets/Post/pp6.png"),
    image: require("./assets/PP/pp6.jpg"),
    hashtags: ["#resep", "#masak"],
  },
  {
    id: 7,
    username: "kucing_pintar",
    time: "3 jam",
    caption: "Diajak belajar malah bobo, dasar meong 🐱📚",
    avatar: require("./assets/Post/pp7.png"),
    image: require("./assets/PP/pp7.jpg"),
    hashtags: ["#kucing", "#lucu"],
  },
  {
    id: 8,
    username: "backpacker_id",
    time: "3 jam 45 menit",
    caption: "Air terjun tersembunyi di balik bukit! 💦🌿",
    avatar: require("./assets/Post/pp8.png"),
    image: require("./assets/PP/pp8.jpeg"),
    hashtags: ["#adventure", "#alam"],
  },
  {
    id: 9,
    username: "musisi_rumahan",
    time: "5 jam",
    caption: "Jamming dadakan sama temen sekos 🎸🔥",
    avatar: require("./assets/Post/pp9.png"),
    image: require("./assets/PP/pp9.jpeg"),
    hashtags: ["#musik", "#santai"],
  },
  {
    id: 10,
    username: "sketmania",
    time: "6 jam",
    caption: "Sketsa iseng jadi viral, kok bisa ya? ✏️🤯",
    avatar: require("./assets/Post/pp10.png"),
    image: require("./assets/PP/pp10.png"),
    hashtags: ["#art", "#sketch"],
  },
];
