export const posts = [
    {
      id: 1,
      username: "juragan_bola",
      time: "17 menit",
      caption: "Kalah sama yang punya 2 hp 😹🤯",
      hashtags: ["#funny", "#olahraga"],
      image: require("./assets/Post/pp1.png"),
      avatar: require("./assets/PP/pp1.jpg"),
    },
    {
      id: 2,
      username: "si_kreatif",
      time: "30 menit",
      caption: "Ngoding tengah malam biar dapat wangsit 👨‍💻🌙",
      hashtags: ["#developer", "#nightlife"],
      image: require("./assets/Post/pp2.png"),
      avatar: require("./assets/PP/pp2.png"),
    },
    {
      id: 3,
      username: "mama_muda",
      time: "1 jam",
      caption: "Masakan pertama anakku bilang enak 😭❤️",
      hashtags: ["#makan", "#keluarga"],
      image: require("./assets/Post/pp3.png"),
      avatar: require("./assets/PP/pp3.jpg"),
    },
    {
      id: 4,
      username: "tukang_ngopi",
      time: "2 jam",
      caption: "Ngopi dulu biar hidup tenang ☕",
      hashtags: ["#kopi", "#santai"],
      image: require("./assets/Post/pp4.png"),
      avatar: require("./assets/PP/pp4.png"),
    },
    {
      id: 5,
      username: "si_pendaki",
      time: "3 jam",
      caption: "Akhirnya sampai puncak! 😍🏔️",
      hashtags: ["#travel", "#gunung"],
      image: require("./assets/Post/pp5.png"),
      avatar: require("./assets/PP/pp5.jpg"),
    },
    {
      id: 6,
      username: "chef_online",
      time: "4 jam",
      caption: "Resep baru, siapa mau coba? 👨‍🍳",
      hashtags: ["#resep", "#masak"],
      image: require("./assets/Post/pp6.png"),
      avatar: require("./assets/PP/pp6.jpg"),
    },
    {
      id: 7,
      username: "cat_lover",
      time: "5 jam",
      caption: "Kucingku belajar baca buku 😺📚",
      hashtags: ["#kucing", "#lucu"],
      image: require("./assets/Post/pp7.png"),
      avatar: require("./assets/PP/pp7.jpg"),
    },
    {
      id: 8,
      username: "si_petualang",
      time: "6 jam",
      caption: "Ketemu air terjun tersembunyi! 💦",
      hashtags: ["#adventure", "#alam"],
      image: require("./assets/Post/pp8.png"),
      avatar: require("./assets/PP/pp8.jpeg"),
    },
    {
      id: 9,
      username: "musik_dulu",
      time: "7 jam",
      caption: "Jamming sore-sore biar waras 🎶",
      hashtags: ["#musik", "#santai"],
      image: require("./assets/Post/pp9.png"),
      avatar: require("./assets/PP/pp9.jpeg"),
    },
    {
      id: 10,
      username: "seniman_sket",
      time: "8 jam",
      caption: "Sketsa baru lagi trending! ✏️",
      hashtags: ["#art", "#sketch"],
      image: require("./assets/Post/pp10.png"),
      avatar: require("./assets/PP/pp10.png"),
    },
  ];
  